### ISSUE TITLE
1.19 please <3

### ISSUE THREAD

**Issue by ghost** [PieKing1215/InvMove#12]

**Comment by PieKing1215** [comment]
Yeah I've already been working on it on this branch: https://github.com/PieKing1215/InvMove/tree/multiversion
If you look in the actions tab there are *WIP* automatic dev builds like [this one](https://github.com/PieKing1215/InvMove/actions/runs/2492532022) and you can click on the file under artifacts to get a zip with the jars for every supported version inside.

I think I'm pretty close to releasing it, but keep in mind I haven't started updating InvMoveCompats so that will come a bit later (the current versions of InvMoveCompats are incompatible).

**Comment by PieKing1215** [comment]
Btw if you didn't see I made an experimental release a couple days ago that supports 1.19/18/16: [v0.8.0](https://github.com/PieKing1215/InvMove/releases/tag/v0.8.0)
It's only available here and on [Modrinth](https://modrinth.com/mod/invmove) right now, I'm waiting until after I fix any bugs and update InvMoveCompats to upload to curseforge.

**Comment by ghost** [comment]
Hello, yep I saw that already. I am testing/playing the mod with many others (190+) and I had no problems at all - even with the Snapshot release:)
If I find any bug I tell you - thanks for the work, love this mod 🥰

**Comment by ghost** [comment]
Hey @PieKing1215,
I found now two issues.

The first mod: **Crawl** https://www.curseforge.com/minecraft/mc-mods/crawl
While you crawling and open your inventory, you have the normal speed.

The second: **Sneaky Screens** https://www.curseforge.com/minecraft/mc-mods/sneaky-screens
While you open your inventory it lopes back from sneaking to standing.

I hope it helps 😊

**Comment by PieKing1215** [comment]
Yeah thanks that's definitely helpful!
Mods that change movement mechanics like that are pretty likely to cause problems, I'll take a look.
(fwiw this mod already has basically the same feature as sneaky screens)

**Comment by PieKing1215** [comment]
[v0.8.1](https://github.com/PieKing1215/InvMove/releases/tag/v0.8.1) fixes new versions of Forge for 1.19 (including 1.19.1)
Since the new build setup hasn't really seemed to cause any bugs, I decided to release it on curseforge finally!
(I also finally got around to finishing my version release script so I don't have to manually create 8 releases on both MR and CF)

I started updating InvMoveCompats for InvMove 0.8.x, and made a [quick release](https://github.com/PieKing1215/InvMoveCompats/releases/tag/v0.2.0) that supports only Forge/Fabric 1.18 for now (it'll eventually get the same crossversion build setup as base InvMove)

So I'm gonna close this for now, if any more issues come up feel free to open another issue!
(I'll look at Crawl/Sneaky Screens for the next update probably)

**Comment by PINPAL** [comment]
Are there any builds on InvMoveCompats for 1.19? I don't see any on Curseforge/Modrinth?

**Comment by PieKing1215** [comment]
See https://github.com/PieKing1215/InvMoveCompats/issues/5#issuecomment-1586557776
