### ISSUE TITLE
Moving away from chest breaks animations

### ISSUE THREAD

**Issue by blackmyin** [PieKing1215/InvMove#14]
When opening a chest with InvMove and moving away from it the animations of the chest breaks. On singleplayer the animations of that specific chest simply stops working and on multiplayer the animations of the chest are reversed (always open, closes on interact).
Temporarily fixed by restarting world.

Tested with 1.19
Fabric Loader 0.14.8
Fabric API 0.55.3+1.19
Cloth Config 7.0.67-fabric
InvMove 1.19-0.8.0-Fabric

**Comment by PieKing1215** [comment]
Yeah this is a bug with vanilla that I've been meaning to make a fix for but I haven't gotten around to it. It's because the server (or internal server) will forcibly close the screen if you go too far from the chest and the way they do it breaks the animation.
I might look into fixing this for the next non-alpha release

**Comment by Khodyn** [comment]
> I might look into fixing this for the next non-alpha release

Might better belong as a [Debugify](https://github.com/isXander/Debugify) PR.

**Comment by PieKing1215** [comment]
Looks like this is fixed since 1.20.5: https://bugs.mojang.com/browse/MC-229680
On some older versions looks like [Carpet-Fixes](https://modrinth.com/mod/carpet-fixes) has a setting to fix it ([viewerCountNegativesFix](https://github.com/fxmorin/carpet-fixes/wiki/Available-Settings#viewercountnegativesfix))

For now I feel like backporting the fix might be out of scope for this mod but open to thoughts
