### ISSUE TITLE
Roughly Enough Items conflict, movement still present when disabled

### ISSUE THREAD

**Issue by moymazzoni** [PieKing1215/InvMove#30]
**Describe the bug**
When using the search bar included with Roughly Enough Items you can still move around when typing something out, even with both "Unrecognized Screens Default" to off and when "DefaultDisplayViewingScreen" is off. It works completely fine with Inmis though.

**To Reproduce**
Either clicking the search bar for REI or by using your custom shortcut to interact/highlight with it, then typing out anything that involves your movement keys.

**Screenshots**
(Don't have any)

**Crash Log**
(No crash log)

**Version and Mod List**
InvMove: v0.8.3
Forge/Fabric/Quilt version: Fabric
Minecraft: 1.19.2

List any other mods being used:
I removed all other mods besides the bare essentials to make these two run, that being the following:

Architectury - v6.5.77
Cloth Config v8 - v8.2.88
Fabric API - v0.76.0+1.19.2
InvMove - v0.8.3
Roughly Enough Items - v9.1.595

**Comment by PieKing1215** [comment]
This happens because REI and similar mods' overlays don't work the same as normal screens, so for them to work I need to specifically add support for each mod.
This is what [InvMoveCompats](https://github.com/PieKing1215/InvMoveCompats) is for, but it still needs some work to finish the update that will make it work with current versions of the base mod.
No promises, but I'm hoping to finally finish the InvMoveCompats update early this summer when I should hopefully have more time.

**Comment by moymazzoni** [comment]
Ah that makes sense. Thanks for the explanation and quick reply, have a good one.

**Comment by notIkibo** [comment]
So Compat Mod won't get future updates anymore? For 1.20.x?
