### ISSUE TITLE
1.20

### ISSUE THREAD

**Issue by AxionQc** [PieKing1215/InvMove#32]
1.20 Support

**Comment by AlwaysDani1** [comment]
pls add 1.20

**Comment by PieKing1215** [comment]
Working on it right now :)

**Comment by AlwaysDani1** [comment]
Yey

**Comment by PieKing1215** [comment]
Alright that should do it! I'll probably release within a few days if nothing major comes up
If you want to try/test it early this run should have artifacts at the bottom once it finishes (hopefully)
https://github.com/PieKing1215/InvMove/actions/runs/5233632251

**Comment by MCRusher** [comment]
I can say that those artifacts for 1.20 work just fine for me with my mod list based on Fabulously Optimized + Extras.

Thanks for this mod btw, I can't play without it anymore.

**Comment by AlwaysDani1** [comment]
I have been using it for the last 2 days and no issues

**Comment by PieKing1215** [comment]
Version [0.8.4](https://github.com/PieKing1215/InvMove/releases/tag/v0.8.4) (with 1.20 support) is out on [Modrinth](https://modrinth.com/mod/invmove/versions)!
I set it as alpha because I didn't have time to manually test every version/loader combo, but I didn't want to keep everyone waiting when it seems like it's working fine (feel free to open issues if there's any problems).
