### ISSUE TITLE
Blur Incompatibility causes dark background to flicker upon exiting menu/GUI

### ISSUE THREAD

**Issue by BLOKBUSTR** [PieKing1215/InvMove#35]
When Blur is present, the dark transparent background flickers once upon closing a GUI. This only happens in GUIs which are set in InvMove's config to "hide background."

GUIs which are configured to have their background shown will not display any issues. There are also no issues with the blurring effect itself, and the flickering does not persist.

I made a fresh installation with only InvMove, Blur, and any other necessary dependencies to confirm that it's indeed a compatibility issue with Blur. In my example video, I configured the background to show in the crafting table UI, but left the default setting for the player inventory:

https://github.com/PieKing1215/InvMove/assets/118950712/b263523c-70b4-4557-8a28-c80e41143d8e

I'm using all the latest versions:
Minecraft 1.20.1
Fabric 0.14.21
InvMove 0.8.4
Blur 3.1.0
Cloth Config 11.1.106

**Comment by PieKing1215** [comment]
Blur has config options that let you configure the background tint
So generally you can just turn off InvMove's `Hide Inventory Backgrounds` if you have Blur
And if you want to have no tint then also go in Blur's settings and set `Gradient Start/End Alpha` to 0
Otherwise you can set the colors/alphas in Blur

(in recent versions the flicker doesn't even happen with default settings, InvMove's background hiding just does nothing)
