### ISSUE TITLE
Move when in jei search bar typing

### ISSUE THREAD

**Issue by Jupitor87** [PieKing1215/InvMove#41]
Move when in jei search bar typing with keys w,a,s,d

**Comment by MendingNights** [comment]
> Move when in jei search bar typing with keys w,a,s,d

Good luck.  The dev for this mod seems to have abandoned it.  We've been waiting almost 2 months for a 1.20.2 update with no response.

**Comment by Fyoncle** [comment]
Good luck for real, mod dev doesnt seem to care EVEN A LITTLE BIT, that glitch not even exist in legacy version, also shoulder surfing is compatible in legacy version, but the new one is not... crazy

**Comment by PieKing1215** [comment]
Hi, I work a full time job and my mods are one of many side projects that I work on in my limited free time.
Maintaining them generally ranks low on the list of interesting things to work on, so usually motivation comes when I personally am playing Minecraft (which I haven't in almost a year).
(looking at it financially the amount of revenue from CF/Modrinth for all of my mods combined equates to under 10 hours per month at minimum wage)

This specific issue is not a glitch, all of JEI/REI/EMI/etc either don't use the vanilla text field widget or don't add it the vanilla way, which means I have to add support for them all individually
The base InvMove mod explicitly does not include anything that requires me to add extra dependencies on other mods, specifically because the legacy version was painful and took forever to update because it depended on like 20 other mods
This is why InvMoveCompats is separate & it *is* getting updated soon (https://github.com/PieKing1215/InvMoveCompats/issues/5#issuecomment-2081858101)

As for shoulder surfing, I have never played with it and didn't know it had problems with InvMove until its dev opened a (very helpful) issue for it last month (gh-49)
The main reason I haven't implemented the fix they suggested yet is because moving where/how I modify player movement significantly changes what mods are compatible, meaning I have to build and retest on several different MC versions with several different sets of mods, which could take several hours of boring grinding just to make sure it doesn't re-break other mods that also mess with player movement
The Legacy version hooked/modified movement in a different way, and so it'll by default work with some mods and not work with others

Sorry if I come off as rude, I do see every issue/comment posted here but I don't have the time/energy to respond to everything.
I appreciate that people care about this mod but I am one person and I can't afford to spend all of my time working on this one project.
In the end this is a free & open source project and if people want they can make PRs and contribute fixes, or just take the code and add in support for whatever they want

(closing this issue since it's the whole point of InvMoveCompats)

**Comment by Fyoncle** [comment]
> Hi, I work a full time job and my mods are one of many side projects that I work on in my limited free time. Maintaining them generally ranks low on the list of interesting things to work on, so usually motivation comes when I personally am playing Minecraft (which I haven't in almost a year). (looking at it financially the amount of revenue from CF/Modrinth for all of my mods combined equates to under 10 hours per month at minimum wage)
> 
> This specific issue is not a glitch, all of JEI/REI/EMI/etc either don't use the vanilla text field widget or don't add it the vanilla way, which means I have to add support for them all individually The base InvMove mod explicitly does not include anything that requires me to add extra dependencies on other mods, specifically because the legacy version was painful and took forever to update because it depended on like 20 other mods This is why InvMoveCompats is separate & it _is_ getting updated soon ([PieKing1215/InvMoveCompats#5 (comment)](https://github.com/PieKing1215/InvMoveCompats/issues/5#issuecomment-2081858101))
> 
> As for shoulder surfing, I have never played with it and didn't know it had problems with InvMove until its dev opened a (very helpful) issue for it last month ([gh-49](https://github.com/PieKing1215/InvMove/issues/49)) The main reason I haven't implemented the fix they suggested yet is because moving where/how I modify player movement significantly changes what mods are compatible, meaning I have to build and retest on several different MC versions with several different sets of mods, which could take several hours of boring grinding just to make sure it doesn't re-break other mods that also mess with player movement The Legacy version hooked/modified movement in a different way, and so it'll by default work with some mods and not work with others
> 
> Sorry if I come off as rude, I do see every issue/comment posted here but I don't have the time/energy to respond to everything. I appreciate that people care about this mod but I am one person and I can't afford to spend all of my time working on this one project. In the end this is a free & open source project and if people want they can make PRs and contribute fixes, or just take the code and add in support for whatever they want
> 
> (closing this issue since it's the whole point of InvMoveCompats)

Thank you for your fast response, I didn't know you had a full time job. And no, you weren't rude, you were very kind in fact.

Since I'm using this pack on all of my instances it ended up annoying me when it seemed like the mod was abandoned and I dropped a stupid comment like that, my apologies for how I reacted.

I hope you find motivation very soon and life gets better, have a nice one and good luck!
