### ISSUE TITLE
le crash

### ISSUE THREAD

**Issue by thelegitdolt** [PieKing1215/InvMove#8]
https://gist.github.com/thelegitdolt/5bb4831cf25673c6eb013a34581a24e1

**Comment by Delfite** [comment]
This appears to be an issue with Quark:

`        at net.minecraft.world.item.Item.handler$zkn000$getDisplayName(Item.java:2534) ~[client-1.18.2-20220404.173914-srg.jar%2397!/:?] {re:mixin,re:classloading,pl:mixin:APP:allurement.mixins.json:ItemMixin,pl:mixin:APP:blueprint.mixins.json:ItemInvokerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.item.AccessItem,pl:mixin:APP:quark.mixins.json:ItemMixin,pl:mixin:APP:structure_gel.mixins.json:ItemMixin,pl:mixin:APP:supplementaries.mixins.json:ItemMixin,pl:mixin:A}`

`	at net.minecraft.world.item.Item.m_7626_(Item.java) ~[client-1.18.2-20220404.173914-srg.jar%2397!/:?] {re:mixin,re:classloading,pl:mixin:APP:allurement.mixins.json:ItemMixin,pl:mixin:APP:blueprint.mixins.json:ItemInvokerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.item.AccessItem,pl:mixin:APP:quark.mixins.json:ItemMixin,pl:mixin:APP:structure_gel.mixins.json:ItemMixin,pl:mixin:APP:supplementaries.mixins.json:ItemMixin,pl:mixin:A}`

`	at net.minecraft.world.item.ItemStack.m_41786_(ItemStack.java:593) ~[client-1.18.2-20220404.173914-srg.jar%2397!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}`

`	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:629) ~[client-1.18.2-20220404.173914-srg.jar%2397!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}`

Try reporting this to Vazkii through their github to see what they can make of this: https://github.com/VazkiiMods/Quark/issues

**Comment by PieKing1215** [comment]
When does this crash actually happen, at launch? I can't reproduce this with IE, Quark, or any of the mods in the crash log.

It looks to me more likely to be a problem with Structure Gel API than Quark. Quark is just one of the several mods listed that happens to mixin into `Item` and `ItemStack` (not necessarily a sign of anything wrong), whereas Structure Gel is actually part of the stacktrace: (though it is possible it's just a red herring)
```
at com.legacy.structure_gel.core.block.DataHandlerBlock.<init>(DataHandlerBlock.java:52) ~[structure_gel-1.18.2-2.2.0.jar%2392!/:2.2.0] {re:mixin,re:classloading}
at com.legacy.structure_gel.core.registry.SGBlocks.lambda$static$6(SGBlocks.java:39) ~[structure_gel-1.18.2-2.2.0.jar%2392!/:2.2.0] {re:mixin,re:classloading,pl:eventbus:A}
```
Looks like it has had several updates since the version this crash log uses so if it was that maybe it has been fixed?

Even so I have no clue how this could have anything to do with InvMove?
It's kind of hard to debug something like this without the full mod list (preferably with only the mods needed to cause the problem), since I can't reproduce the error otherwise.

**Comment by PieKing1215** [comment]
Closing this for now since I cannot reproduce without more information
